In [1]:
from numpy import array
from numpy.linalg import norm
from gnss.coordinates import ecef2enu, ecef2geo, ecef2sky, geo2ecef, geo2sky

In [2]:
rx_geo = array([39.5, -84.7, 251.])
rx_ecef = array([455.24e3, -4907.3e3, 4035.5e3])
sat_ecef = array([16361e3, 6029e3, 20213e3])

In [3]:
ecef2geo(sat_ecef)

array([  4.92631199e+01,   2.02287542e+01,   2.03286272e+07])

In [4]:
print(ecef2geo(rx_ecef))
print(geo2ecef(rx_geo.reshape((1,3))))
print(ecef2enu(rx_ecef, sat_ecef))
print(ecef2sky(rx_ecef, sat_ecef))

[  39.50042191  -84.69995899  252.06752778]
[  455239.16353163 -4907329.17522665  4035463.17518235]
[ 16847957.2741348   18474986.91820225   3021350.55542778]
[ 42.36273153   6.89002974]


In [5]:
r_e = 6371e3
a = array([1., 1., 1.])
b = array([0., 0., -.1])
a = a / norm(a) * r_e
b = b / norm(a) * 3 * r_e
print(' '.join([str(x) for x in ecef2enu(a, b)]))
print(ecef2sky(a, b))

-4.65661287308e-10 20195.0900986 -6370968.16546
[ -1.32113431e-12  -8.98183809e+01]
