In [1]:
from numpy import pi, zeros, ones, flatnonzero, sin, cos, tan, radians, asarray, sqrt, absolute, \
                  column_stack, nan, nanmean, identity, isnan, where
import numpy
numpy.set_printoptions(threshold=nan)
npmax = numpy.max
npsum = numpy.sum
from numpy.linalg import norm, inv, LinAlgError

import pytz

from gnss.time import gpstime, utctime
from gnss.parsing import read_novatel_ascii
from gnss.orbits import compute_gps_satellite_position_from_orbital_parameters, compute_gps_orbital_parameters_from_ephemeris
from gnss.coordinates import ecef2geo, ecef2sky, geo2ecef
from gnss.positioning import TroposphereDelayModel, HopfieldModel, SaastomoinenModel, IonosphereDelayModel

there are 27 leap second epochs


$$
% commands
\newcommand{\state}{\text{state}}
\newcommand{\clockbias}{dt}
\newcommand{\clockrate}{\dot{dt}}
$$

Our state consists of position coordinates, integer ambiguities for each satellite ($N_i$, $i \in \{0, 31\}), and clock bias and drift.

$$
\state = (x, y, z, N_1, ..., N_n, \clockbias, \clockrate) \\
Z_k = f_k(\state_k) =
\left(\begin{array}[c] \\
\sqrt{(x - x^{(0)})^2 + (y - y^{(0)})^2 + (z - z^{(0)})^2} + \clockbias \cdot c \\
... \\
\sqrt{(x - x^{(n)})^2 + (y - y^{(n)})^2 + (z - z^{(n)})^2} + \clockbias \cdot c \\
\frac{1}{\lambda}\sqrt{(x - x^{(0)})^2 + (y - y^{(0)})^2 + (z - z^{(0)})^2} + N + \clockbias \cdot \frac{c}{\lambda} \\
... \\
\frac{1}{\lambda}\sqrt{(x - x^{(n)})^2 + (y - y^{(n)})^2 + (z - z^{(n)})^2} + N + \clockbias \cdot \frac{c}{\lambda}
\end{array}\right)
$$

$H_k$ is the Jacobian of $f_k$. Note that $g(x) = \sqrt{(x - a)^2 + b} + c$ near $x_0$ is $g(x_0) + \frac{(x_0 - a)}{\sqrt{(x_0 - a)^2 + b}}(x - x_0) + O(x^2)$

Then to first-order approximation around our state estimate $(\hat{x}, \hat{y}, \hat{z}, ...)$, we have:

$$
H_k = 
\left(\begin{array}[c] \\
\frac{(\hat{x} - x^{(0)})}{\hat{r}^{(0)}} & \frac{(\hat{y} - y^{(0)})}{\hat{r}^{(0)}} & \frac{(\hat{z} - z^{(0)})}{\hat{r}^{(0)}} & 0 &  & ... & c & 0 \\
... \\
\frac{(\hat{x} - x^{(n)})}{\hat{r}^{(n)}} & \frac{(\hat{y} - y^{(n)})}{\hat{r}^{(n)}} & \frac{(\hat{z} - z^{(n)})}{\hat{r}^{(n)}} & 0 &  & ... & c & 0 \\
\frac{1}{\lambda}\frac{(\hat{x} - x^{(0)})}{\hat{r}^{(0)}} & \frac{1}{\lambda}\frac{(\hat{y} - y^{(0)})}{\hat{r}^{(0)}} & \frac{1}{\lambda}\frac{(\hat{z} - z^{(0)})}{\hat{r}^{(0)}} & 1 & 0 & ... & \frac{c}{\lambda} & 0 \\
... \\
\frac{1}{\lambda}\frac{(\hat{x} - x^{(n)})}{\hat{r}^{(n)}} & \frac{1}{\lambda}\frac{(\hat{y} - y^{(n)})}{\hat{r}^{(n)}} & \frac{1}{\lambda}\frac{(\hat{z} - z^{(n)})}{\hat{r}^{(n)}} & 0 & ... & 1 & \frac{c}{\lambda} & 0 \\
\end{array}\right)
$$

where

$$
\hat{r} = \sqrt{(\hat{x} - x^{(0)})^2 + (\hat{y} - y^{(n)})^2 + (\hat{z} - z^{(n)})^2}
$$

If "$g(\state)$" is "range for $\state^-_k$", then we have

$$
\Delta Z^{(i)}_k = \rho^{(i)}_{\text{meas}} - \rho^{(i)}_{\text{est}} = \rho^{(i)}_{\text{meas}} - \hat{r}^{i} - \clockbias \cdot c
$$

of for the case of phase

$$
\Delta Z^{(i)}_k = \phi^{(i)}_{\text{meas}} - \phi^{(i)}_{\text{est}} = \phi^{(i)}_{\text{meas}} - \hat{r}^{i} / \lambda - \clockbias \cdot c / \lambda - N^{(i)}
$$

where $\rho^{(i)}_{\text{meas}} $ and $\phi^{(i)}_{\text{meas}}$ are ionosphere/troposphere and satellite clock bias-free.

Note that phase is in units of cycles.

The Kalman filter equations are then:

$$
\text{propagate} \\
\state^-_{k} = \Phi(\state^+_{k-1}) \\
P^-_{k} = P^+_{k-1} \\
\\
\text{update} \\
\state^+_{k} = \state^-_{k} + K(z_k 
$$

In [2]:
# novatel_filepath = './../../data/20131119d.gps'  # 41 deg F, 28 dew point, 1025 hPa barometric pressure  (phase iono)
novatel_filepath = './../../data/20131119a.gps'  # same    (don't use iono on this one)
T = 278    # K
P0 = 1025  # mbar
e0 = 5.19  # mbar
rh = 0.60  # relative humidity
e0 = TroposphereDelayModel.h20_partial_pressure_from_relative_humidity(rh, T)

In [3]:
observations, ephemerides, bestpos = read_novatel_ascii(novatel_filepath)

In [4]:
filedate = utctime(bestpos.time[0])
print(filedate, filedate.astimezone(pytz.timezone('US/Eastern')))

2013-11-19 20:42:23+00:00 2013-11-19 15:42:23-05:00


In [5]:
bestpos.ecef = geo2ecef(bestpos.geo)
rx_geo_ref = bestpos.geo[0, :]
rx_ecef_ref = bestpos.ecef[0, :]
print(rx_geo_ref, rx_ecef_ref)

[  39.51069221  -84.7322822   293.7752    ] [  452407.84641097 -4906865.73686049  4036406.35445183]


In [6]:
c = 299792458.                # Speed of light in vacuum (m/s)
omega_e_dot = 7.2921159e-5    # Earth's andular rotation rate (rad/s)
f_carr_l1 = 1.57542e9         # GPS L1 frequency
f_carr_l2 = 1.22760e9         # GPS L2 frequency
lambda_l1 = c / f_carr_l1     # GPS L1 wavelength
lambda_l2 = c / f_carr_l2     # GPS L2 wavelength
cnr_threshold = 30.           # carrier-to-noise-ratio threshold

In [7]:
iono_model = IonosphereDelayModel(f_carr_l1, f_carr_l2)
tropo_model = SaastomoinenModel(P0, e0, T, rx_geo_ref[0], rx_geo_ref[2])
print(tropo_model.dry_zenith_delay, tropo_model.wet_zenith_delay)

0.00227831475766 0.0528486997846


In [8]:
SIZE = len(observations[1].time)
print('Total number of observations: {0}'.format(SIZE))

# preallocation
sv_ecef = {}
sv_range = {}
sv_phase = {}
sv_ambiguity = {}
rx_ecef = zeros((SIZE, 3))
rx_geo = zeros((SIZE, 3))
dop = zeros((SIZE, 4))

rx_ecef[:] = nan
rx_geo[:] = nan
dop[:] = nan

Total number of observations: 3316


In [36]:
# static solution
step = 1  # second

# state vector: x, y, z, N1, N2, ..., Nn, b, b_rate <-- clock bias in meters!
state = zeros((37,))
state[:3] = rx_ecef_ref
state[35] = 34.

# state covariance matrix
P = 100 * identity(37)

# state transition matrix (propagation)
Phi = zeros((37, 37))
Phi[:35, :35] = identity(35)
Phi[35:, 35:] = asarray([[1, step], [0, 1]])

# spectral amplitude of position error, integer ambiguity error, and clock bias/bias rate error
S_p = S_a = S_c = 1.

# process noise matrix
Q = zeros((37, 37))
Q[:35, :35] = identity(35)
Q[35:, 35:] = S_c * asarray([[step**3 / 3, step**2 / 2], [step**2 / 2, step]])

# observation covariance matrix TODO
# R
# H is the linear relationship of measurement to state and is computed each loop
# dz is the measurement innovation vector

In [37]:
# compute initial integer ambiguity states
for i, svid in enumerate(range(1, 33)):
    obs = observations[svid]
    first_obs_index = where(~isnan(obs.l1.psr))[0]
    if not any(first_obs_index):
        continue
    first_obs_index = first_obs_index[0]
    initial_N = round((obs.l1.psr[first_obs_index] - (-obs.l1.adr[first_obs_index] * lambda_l1)) / lambda_l1)
    print(svid, first_obs_index, initial_N, obs.l1.psr[first_obs_index], obs.l1.adr[first_obs_index])
    state[2 + svid] = initial_N
# state[2 + 15] = 0.

2 0 78.0 24644154.403 -129505827.653
5 0 -74.0 23221810.859 -122031514.096
6 1045 -3.0 24950914.774 -131117945.599
8 0 13.0 25182690.758 -132335920.155
9 0 1.0 24209320.403 -127220836.675
15 0 -183.0 20358764.666 -106986213.318
16 0 -0.0 25775721.33 -135452329.974
18 0 -64.0 22721905.425 -119404482.489
21 0 -67.0 22074606.499 -116002906.887
22 1061 -0.0 25077544.429 -131783385.448
24 0 -3.0 25151687.44 -132173012.883
26 0 -135.0 20655872.731 -108547478.599
29 0 10.0 21557216.81 -113283929.394


In [38]:
# %%time
skipped_epochs = 0

for page in range(0, 10): #SIZE):
    
    # propagate state and state covariance
    state = Phi.dot(state)
    P = Phi.dot(P).dot(Phi.T) + Q
        
    # get current state parameters
    rx_ecef_est = state[:3]
    integer_ambiguity = state[2 + valid_svids]
    clock_bias = state[35]
    
    # mask unsuitable svids (we need at least four valid measurements for positioning)
    valid_svids = asarray([svid for svid, obs in observations.items() if obs.l1.cnr[page] > cnr_threshold and obs.l1.psr[page] > 0 and obs.l1.psr[page] < 2.6e7])
    if len(valid_svids) < 4:
        skipped_epochs += 1
        continue
        
    # clean measurements for each sv
    for i, svid in enumerate(valid_svids):  # TODO does enumerate exactly follow ordering of valid_svids
        # get relevant observations/ephemerides
        obs = observations[svid]
        eph = ephemerides[svid]
        # estimate propagation time and transmission time
        tau = obs.l1.psr[page] / c
        sv_time = obs.time[page] - tau  # => + 72m error w/o
        # compute satellite position
        u, r, i, Omega, n, E = compute_gps_orbital_parameters_from_ephemeris(eph, sv_time)
        sv_ecef[svid] = compute_gps_satellite_position_from_orbital_parameters(u, r, i, Omega)
        # compute satellite clock drift error and relativistic corrections
        sv_time_correction_epoch = eph.zweek * 604800 + eph.t_oc
        elapsed_time = sv_time - sv_time_correction_epoch
        sv_time_diff = eph.a0 + eph.a1 * elapsed_time + eph.a2 * elapsed_time**2 \
                        - 4.442807633e-10 * eph.e * sqrt(eph.a) * sin(E)
        # compute satellite sky coordinates to get obliquity
        sv_sky = ecef2sky(rx_ecef_ref, sv_ecef[svid])
        el = radians(sv_sky[1])
        # correct ECEF for Earth rotation
        theta = omega_e_dot * tau
        rot_omega_e = asarray([[cos(theta), sin(theta), 0],
                               [-sin(theta), cos(theta), 0],
                               [0, 0, 1]])
        sv_ecef[svid] = rot_omega_e.dot(sv_ecef[svid].T).T
        # compute partially cleaned carrier phase measurements
        adr_l1_c = obs.l1.adr[page] + c * sv_time_diff / lambda_l1
        adr_l2_c = obs.l2.adr[page] + c * sv_time_diff / lambda_l2
        # compute tec and ionospheric/tropospheric delays
        iono_delay = iono_model.delay(obs.l1.psr[page], obs.l2.psr[page])
        tropo_delay = tropo_model.delay(el)
        
        # compute cleaned pseudorange/phase; sv_time_diff => +160km pos error, tropo_error => 15m error, iono -2m error
        sv_range[svid] = obs.l1.psr[page] + c * sv_time_diff - clock_bias - tropo_delay - iono_delay
        sv_phase[svid] = -obs.l1.adr[page] + (c * sv_time_diff - clock_bias - tropo_delay + iono_delay) / lambda_l1 - integer_ambiguity[i]

    # linearized observation model
#     H[:, :] = 0.
#     for svid in valid_svids:
#         r_hat = norm(sv_ecef[svid] - rx_ecef_ref)
#         H[svid - 1, :3] = H[31 + svid, :3] = (rx_ecef_est - sv_ecef[svid]) / r_hat
#         H[31 + svid, :3] /= lambda_l1
#         H[svid - 1, 3:] = 0.
#         H[31 + svid, 3:] = 0.
#         H[31 + svid, 2 + svid] = 1.
#         H[svid - 1, 35] = c
#         H[31 + svid, 35] = c / lambda_l1
    n_svs = len(valid_svids)
    H = zeros((2 * n_svs, 3 + n_svs + 2))  # todo still do each integer ambiguity?
    for i, svid in enumerate(valid_svids):
        r_hat = norm(sv_ecef[svid] - rx_ecef_ref)
        H[i, :3] = H[n_svs + i, :3] = (rx_ecef_est - sv_ecef[svid]) / r_hat
        H[n_svs + i, :3] /= lambda_l1
        H[i, 3:] = 0.
        H[n_svs + i, 3:] = 0.
        H[n_svs + i, 3 + i] = 1.
        H[i, 3 + n_svs] = 1.  # in meters
        H[n_svs + i, 3 + n_svs] = 1. / lambda_l1
        
    # TODO: every time satellite comes into view, need to reset it's P matrix
    
    # choose our P matrix
    state_indices = numpy.concatenate(([0, 1, 2], valid_svids - 1, [35, 36]))
    P_indices = numpy.ix_(state_indices, state_indices)
    P_tmp = P[P_indices]
    # calculate Kalman gain
    K = P_tmp.dot(H.T).dot(inv(H.dot(P_tmp).dot(H.T) + 0.1 * identity(2 * n_svs)))
    # compute innovation
    dz = zeros((2 * n_svs,))
    for i, svid in enumerate(valid_svids):
        # pseudorange
        dz[i] = sv_range[svid] - norm(sv_ecef[svid] - rx_ecef_ref)
        # phase
        dz[n_svs + i] = sv_phase[svid] - norm(sv_ecef[svid] - rx_ecef_ref) / lambda_l1

    # update state and state covariance
    update = K.dot(dz)

    state[state_indices] = state[state_indices] + update
#     state[:3] = state[:3] + update[:3]
#     state[2 + valid_svids] = state[2 + valid_svids] - update[3:3 + len(valid_svids)]
#     state[35:] = state[35:] + update[35:]
    P_tmp = (identity(len(state_indices)) - K.dot(H)).dot(P_tmp)
    P[P_indices] = P_tmp
    
    rx_ecef[page, :] = state[:3]

print('done')

done


In [39]:
print(state[:3])
print(state[3:35])
print(state[35:37])
print(norm(rx_ecef_ref - state[:3]))

[  452610.89787249 -4906825.04627446  4036168.31944323]
[  0.00000000e+00   2.57368567e+02   0.00000000e+00   0.00000000e+00
  -9.49467386e+02  -9.13800251e+02   0.00000000e+00   1.30000000e+01
   1.00000000e+00   0.00000000e+00   0.00000000e+00   1.01051846e+03
  -2.17854130e+02   0.00000000e+00  -1.63244239e+03   0.00000000e+00
   0.00000000e+00  -2.21328230e+03   0.00000000e+00   0.00000000e+00
   1.56201682e+03   0.00000000e+00   3.01904176e+02  -3.00000000e+00
   0.00000000e+00  -1.15442163e+03   0.00000000e+00   0.00000000e+00
   1.00000000e+01   0.00000000e+00   0.00000000e+00   0.00000000e+00]
[-14.11900596  -6.3956382 ]
315.509564251


In [90]:
print(K)

[[ -2.38906839e-01   3.58417948e-01  -6.11264483e-02  -7.81680914e-02
   -1.65490384e-01   2.71486284e-01   1.00267142e-01  -6.11017849e-02
   -2.25053352e-01   9.95896210e-02  -1.24180407e-03   1.86300596e-03
   -3.17726661e-04  -4.06306719e-04  -8.60195685e-04   1.41114743e-03
    5.21174468e-04  -3.17598464e-04  -1.16979560e-03   5.17652810e-04]
 [ -1.24050809e-02  -4.12117497e-01  -2.84923776e-01  -2.56671366e-01
    4.62890779e-01   4.30905470e-02   2.25827708e-01  -1.23567979e-01
    2.43944876e-01   1.14131195e-01  -6.44798618e-05  -2.14212865e-03
   -1.48099362e-03  -1.33414158e-03   2.40604101e-03   2.23978588e-04
    1.17382059e-03  -6.42288934e-04   1.26799107e-03   5.93237863e-04]
 [ -3.77235778e-02   1.86481253e-01   5.60240100e-02   3.47320511e-02
   -3.78131901e-01  -1.35063201e-02  -3.46440215e-01   5.98975823e-01
   -3.77724582e-01   2.77050632e-01  -1.96081839e-04   9.69303264e-04
    2.91204906e-04   1.80532305e-04  -1.96547631e-03  -7.02039480e-05
   -1.80074740e-03

In [89]:
state

array([ -2.89969501e+09,   1.93118444e+10,  -1.76844152e+10,
         0.00000000e+00,  -4.04539634e+09,   0.00000000e+00,
         0.00000000e+00,  -1.03170212e+10,   1.26975144e+09,
         0.00000000e+00,   1.30000000e+01,   1.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   7.03639601e+08,
         2.28988325e+09,   0.00000000e+00,   2.25478693e+09,
         0.00000000e+00,   0.00000000e+00,  -1.92346000e+10,
         0.00000000e+00,   0.00000000e+00,   7.35691749e+09,
         0.00000000e+00,   3.20702369e+09,  -3.00000000e+00,
         0.00000000e+00,   5.10217276e+09,   0.00000000e+00,
         0.00000000e+00,   1.00000000e+01,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,  -2.66002983e+10,
        -2.26204829e+10])

In [58]:
rx_geo = ecef2geo(rx_ecef)

In [59]:
geo_ref = nanmean(bestpos.geo, axis=0)

In [60]:
ecef_diff = norm(rx_ecef - bestpos.ecef, axis=-1)
print(nanmean(ecef_diff))
print(nanmean(rx_ecef, axis=0) - nanmean(bestpos.ecef, axis=0))
print(nanmean(rx_ecef - bestpos.ecef, axis=0))
# print(nanmean(bestpos.ecef, axis=0))
print(geo_ref)

201660775.964
[ -4.41757224e+07   7.04067626e+07  -1.83260739e+08]
[ -4.41757224e+07   7.04067626e+07  -1.83260739e+08]
[  452703.88379013 -4906915.80846909  4036272.34428518]
[  39.50931953  -84.72890811  267.95972231]


In [ ]:
for page in range(0, SIZE):
    x = Phi * x
    P = Phi * P * Phi.T + Q
    
    # compute H matrix
    
    K = P * H.T * inv(H * P * H.T + R)
    x = x + K * (z - H * x)
    P = (identity(37) - K * H) * P

In [ ]:
    # old LSI estimate loop
    while(norm(dx) > .01 and absolute(db) > .01):
        # compute dp
        x_diff = zeros((len(valid_svids), 3))
        for i, svid in enumerate(valid_svids):
            x_diff[i, :] = sv_ecef[svid] - x0
        x_norm = norm(x_diff, axis=1) # compute norm along rows
        p0 = x_norm + b0
        dp = asarray([sv_range[svid] for svid in valid_svids]) - p0

        # compute geometry matrix
        unit = (x_diff.T / x_norm).T # Nx3 broadcast divide NxNone -> 3xN / Nx1
        g = ones((len(valid_svids), 4))
        g[:, 0:3] = -unit

        # solve for dx and db
        try:
            delta = inv(g.T.dot(g)).dot(g.T).dot(dp)
        except LinAlgError:
            skipped_epochs += 1
            continue
            
        dx = delta[0:3]
        db = delta[3]

        # calculate new x and b
        x0 += dx
        b0 += db

.

.

.

.

.

.

.

In [12]:
# initial state for KF
step = 1.  # step size 1 second (TODO update in loop?)
state = asarray([452703., -4906915., 4036272., 0, 0, 0])  # initial state (position, velocity)
P = 10000 * identity(6)  # state covariance matrix
Phi = identity(6)
Phi[[0, 1, 2], [3, 4, 5]] = step  # transition matrix
q_p = 1.
q_v = 1.
Q = zeros((6, 6))  # process noise matrix (effect of incorrect modeling over time)
Q[0, 0] = Q[1, 1] = Q[2, 2] = q_p * step + q_v * step**3
Q[3, 3] = Q[4, 4] = Q[5, 5] = q_v * step
Q[0, 3] = Q[3, 0] = Q[1, 4] = Q[4, 1] = Q[2, 5] = Q[5, 2] = q_v * step**2 / 2.
# z  # measurement vector
# R  # measurement covariance matrix
# H  # linear relationship of measurement to state
print(state)
print(P)
print(Phi)
print(Q)

[  452703. -4906915.  4036272.        0.        0.        0.]
[[ 10000.      0.      0.      0.      0.      0.]
 [     0.  10000.      0.      0.      0.      0.]
 [     0.      0.  10000.      0.      0.      0.]
 [     0.      0.      0.  10000.      0.      0.]
 [     0.      0.      0.      0.  10000.      0.]
 [     0.      0.      0.      0.      0.  10000.]]
[[ 1.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]
[[ 2.   0.   0.   0.5  0.   0. ]
 [ 0.   2.   0.   0.   0.5  0. ]
 [ 0.   0.   2.   0.   0.   0.5]
 [ 0.5  0.   0.   1.   0.   0. ]
 [ 0.   0.5  0.   0.   1.   0. ]
 [ 0.   0.   0.5  0.   0.   1. ]]


In [94]:
from lightning import Lightning

In [17]:
lgn = Lightning(host='http://192.168.3.137:3000/')

In [75]:
# lgn.create_session('pvt-2')
lgn.use_session(2)

Session number: 2

In [95]:
lgn.plot(data={'latitude': geo_ref[0], 'longitude': geo_ref[1], 
               'api_key': 'AIzaSyDcxotfylh6ylNGW9oj-0sv7y_aUHnY_vU', 'points': rx_geo},
        type='geodetic-scatter-plot')

.

.

.

.