In [1]:
from numpy import pi, zeros, ones, flatnonzero, sin, cos, tan, radians, asarray, sqrt, absolute, \
                  column_stack, nan, nanmean, identity, isnan
import numpy
numpy.set_printoptions(threshold=nan)
npmax = numpy.max
npsum = numpy.sum
from numpy.linalg import norm, inv, LinAlgError

import pytz

from gnss.time import gpstime, utctime
from gnss.parsing import read_novatel_ascii
from gnss.orbits import compute_gps_satellite_position_from_orbital_parameters, compute_gps_orbital_parameters_from_ephemeris
from gnss.coordinates import ecef2geo, ecef2sky, geo2ecef
from gnss.positioning import TroposphereDelayModel, HopfieldModel, SaastomoinenModel, IonosphereDelayModel

there are 27 leap second epochs


$$
% commands
\newcommand{\state}{\text{state}}
\newcommand{\clockbias}{dt}
\newcommand{\clockrate}{\dot{dt}}
$$

Our state consists of position coordinates, integer ambiguities for each satellite ($N_i$, $i \in \{0, 31\}), and clock bias and drift.

$$
\state = (x, y, z, N_1, ..., N_n, \clockbias, \clockrate) \\
Z_k = f_k(\state_k) =
\left(\begin{array}[c] \\
\sqrt{(x - x^{(0)})^2 + (y - y^{(0)})^2 + (z - z^{(0)})^2} + \clockbias \cdot c \\
... \\
\sqrt{(x - x^{(n)})^2 + (y - y^{(n)})^2 + (z - z^{(n)})^2} + \clockbias \cdot c \\
\frac{1}{\lambda}\sqrt{(x - x^{(0)})^2 + (y - y^{(0)})^2 + (z - z^{(0)})^2} + N + \clockbias \cdot \frac{c}{\lambda} \\
... \\
\frac{1}{\lambda}\sqrt{(x - x^{(n)})^2 + (y - y^{(n)})^2 + (z - z^{(n)})^2} + N + \clockbias \cdot \frac{c}{\lambda}
\end{array}\right)
$$

$H_k$ is the Jacobian of $f_k$. Note that $g(x) = \sqrt{(x - a)^2 + b} + c$ near $x_0$ is $g(x_0) + \frac{(x_0 - a)}{\sqrt{(x_0 - a)^2 + b}}(x - x_0) + O(x^2)$

Then to first-order approximation around our state estimate $(\hat{x}, \hat{y}, \hat{z}, ...)$, we have:

$$
H_k = 
\left(\begin{array}[c] \\
\frac{(\hat{x} - x^{(0)})}{\hat{r}^{(0)}} & \frac{(\hat{y} - y^{(0)})}{\hat{r}^{(0)}} & \frac{(\hat{z} - z^{(0)})}{\hat{r}^{(0)}} & 0 &  & ... & c & 0 \\
... \\
\frac{(\hat{x} - x^{(n)})}{\hat{r}^{(n)}} & \frac{(\hat{y} - y^{(n)})}{\hat{r}^{(n)}} & \frac{(\hat{z} - z^{(n)})}{\hat{r}^{(n)}} & 0 &  & ... & c & 0 \\
\frac{1}{\lambda}\frac{(\hat{x} - x^{(0)})}{\hat{r}^{(0)}} & \frac{1}{\lambda}\frac{(\hat{y} - y^{(0)})}{\hat{r}^{(0)}} & \frac{1}{\lambda}\frac{(\hat{z} - z^{(0)})}{\hat{r}^{(0)}} & 1 & 0 & ... & \frac{c}{\lambda} & 0 \\
... \\
\frac{1}{\lambda}\frac{(\hat{x} - x^{(n)})}{\hat{r}^{(n)}} & \frac{1}{\lambda}\frac{(\hat{y} - y^{(n)})}{\hat{r}^{(n)}} & \frac{1}{\lambda}\frac{(\hat{z} - z^{(n)})}{\hat{r}^{(n)}} & 0 & ... & 1 & \frac{c}{\lambda} & 0 \\
\end{array}\right)
$$

where

$$
\hat{r} = \sqrt{(\hat{x} - x^{(0)})^2 + (\hat{y} - y^{(n)})^2 + (\hat{z} - z^{(n)})^2}
$$

If "$g(\state)$" is "range for $\state^-_k$", then we have

$$
\Delta Z^{(i)}_k = \rho^{(i)}_{\text{meas}} - \rho^{(i)}_{\text{est}} = \rho^{(i)}_{\text{meas}} - \hat{r}^{i} - \clockbias \cdot c
$$

of for the case of phase

$$
\Delta Z^{(i)}_k = \phi^{(i)}_{\text{meas}} - \phi^{(i)}_{\text{est}} = \phi^{(i)}_{\text{meas}} - \hat{r}^{i} / \lambda - \clockbias \cdot c / \lambda - N^{(i)}
$$

where $\rho^{(i)}_{\text{meas}} $ and $\phi^{(i)}_{\text{meas}}$ are ionosphere/troposphere and satellite clock bias-free.

Note that phase is in units of cycles.

The Kalman filter equations are then:

$$
\text{propagate} \\
\state^-_{k} = \Phi(\state^+_{k-1}) \\
P^-_{k} = P^+_{k-1} \\
\\
\text{update} \\
\state^+_{k} = \state^-_{k} + K(z_k 
$$

Velocity does not impact ranges but only range differences...

In [2]:
# novatel_filepath = './../../data/20131119d.gps'  # 41 deg F, 28 dew point, 1025 hPa barometric pressure  (phase iono)
novatel_filepath = './../../data/20131119a.gps'  # same    (don't use iono on this one)
T = 278    # K
P0 = 1025  # mbar
e0 = 5.19  # mbar
rh = 0.60  # relative humidity
e0 = TroposphereDelayModel.h20_partial_pressure_from_relative_humidity(rh, T)

In [3]:
observations, ephemerides, bestpos = read_novatel_ascii(novatel_filepath)

In [4]:
obs = observations[6]

In [5]:
filedate = utctime(bestpos.time[0])
print(filedate, filedate.astimezone(pytz.timezone('US/Eastern')))

2013-11-19 20:42:23+00:00 2013-11-19 15:42:23-05:00


In [6]:
bestpos.ecef = geo2ecef(bestpos.geo)
rx_geo_ref = bestpos.geo[0, :]
rx_ecef_ref = bestpos.ecef[0, :]
print(rx_geo_ref, rx_ecef_ref)

[  39.51069221  -84.7322822   293.7752    ] [  452407.84641097 -4906865.73686049  4036406.35445183]


In [7]:
tropo_model = SaastomoinenModel(P0, e0, T, rx_geo_ref[0], rx_geo_ref[2])
print(tropo_model.dry_zenith_delay, tropo_model.wet_zenith_delay)

0.00227831475766 0.0528486997846


In [8]:
c = 299792458.                # Speed of light in vacuum (m/s)
omega_e_dot = 7.2921159e-5    # Earth's andular rotation rate (rad/s)
f_carr_l1 = 1.57542e9         # GPS L1 frequency
f_carr_l2 = 1.22760e9         # GPS L2 frequency
lambda_l1 = c / f_carr_l1     # GPS L1 wavelength
lambda_l2 = c / f_carr_l2     # GPS L2 wavelength
cnr_threshold = 30.           # carrier-to-noise-ratio threshold

In [9]:
SIZE = len(observations[1].time)
print('Total number of observations: {0}'.format(SIZE))

# preallocation
sv_ecef = {}
sv_range = {}
sv_phase = {}
rx_ecef = zeros((SIZE, 3))
rx_geo = zeros((SIZE, 3))
dop = zeros((SIZE, 4))

rx_ecef[:] = nan
rx_geo[:] = nan
dop[:] = nan

Total number of observations: 3316


In [30]:
# static solution
step = 1  # second

# state vector: x, y, z, vx, vy, vz, b, b_rate <-- clock bias in meters!
state = zeros((8,))
state[:3] = [452703., -4906915., 4036272.]

# state covariance matrix
P = 10 * identity(8)

# state transition matrix (propagation)
Phi = identity(8)
Phi[:3, 3:6] = identity(3)
Phi[6:, 6:] = asarray([[1, step], [0, 1]])

# spectral amplitude of position error, integer ambiguity error, and clock bias/bias rate error
S_p = S_a = S_c = .1

# process noise matrix
Q = identity(8)
q_p = 1.
q_v = 1.
Q[0, 0] = Q[1, 1] = Q[2, 2] = q_p * step + q_v * step**3
Q[3, 3] = Q[4, 4] = Q[5, 5] = q_v * step
Q[0, 3] = Q[3, 0] = Q[1, 4] = Q[4, 1] = Q[2, 5] = Q[5, 2] = q_v * step**2 / 2.
Q[6:, 6:] = S_c * asarray([[step**3 / 3, step**2 / 2], [step**2 / 2, step]])

# observation covariance matrix TODO
# R
# H is the linear relationship of measurement to state and is computed each loop
# dz is the measurement innovation vector

In [ ]:
# static solution
step = 1  # second

# state vector: x, y, z, vx, vy, vz, b, b_rate <-- clock bias in meters!
state = zeros((8,))
state[:3] = [452703., -4906915., 4036272.]

# state transition matrix (propagation)
Phi = identity(8)
Phi[:3, 3:6] = identity(3)
Phi[6:, 6:] = asarray([[1, step], [0, 1]])



In [31]:
# %%time
skipped_epochs = 0

for page in range(0, SIZE):
    
    # propagate state and state covariance
    state = Phi.dot(state)
    P = Phi.dot(P).dot(Phi.T) + Q
    
    # mask unsuitable svids (we need at least four valid measurements for positioning)
    valid_svids = asarray([svid for svid, obs in observations.items() if obs.l1.cnr[page] > cnr_threshold and obs.l1.psr[page] > 0 and obs.l1.psr[page] < 2.6e7])
    if len(valid_svids) < 4:
        skipped_epochs += 1
        continue
    # clean measurements for each sv
    for svid in valid_svids:
        # get relevant observations/ephemerides
        obs = observations[svid]
        eph = ephemerides[svid]
        # estimate propagation time and transmission time
        tau = obs.l1.psr[page] / c
        sv_time = obs.time[page] - tau  # => + 72m error w/o
        # compute satellite position
        u, r, i, Omega, n, E = compute_gps_orbital_parameters_from_ephemeris(eph, sv_time)
        sv_ecef[svid] = compute_gps_satellite_position_from_orbital_parameters(u, r, i, Omega)
        # compute satellite clock drift error and relativistic corrections
        sv_time_correction_epoch = eph.zweek * 604800 + eph.t_oc
        elapsed_time = sv_time - sv_time_correction_epoch
        sv_time_diff = eph.a0 + eph.a1 * elapsed_time + eph.a2 * elapsed_time**2 \
                        - 4.442807633e-10 * eph.e * sqrt(eph.a) * sin(E)
        # compute satellite sky coordinates to get obliquity
        sv_sky = ecef2sky(rx_ecef_ref, sv_ecef[svid])
        el = radians(sv_sky[1])
        # correct ECEF for Earth rotation
        theta = omega_e_dot * tau
        rot_omega_e = asarray([[cos(theta), sin(theta), 0],
                               [-sin(theta), cos(theta), 0],
                               [0, 0, 1]])
        sv_ecef[svid] = rot_omega_e.dot(sv_ecef[svid].T).T
        # compute partially cleaned carrier phase measurements
        adr_l1_c = obs.l1.adr[page] + c * sv_time_diff / lambda_l1
        adr_l2_c = obs.l2.adr[page] + c * sv_time_diff / lambda_l2
        # compute tec and ionospheric/tropospheric delays
        tropo_delay = tropo_model.delay(el)
        # TODO ionosphere delay
        # compute cleaned pseudorange/phase; sv_time_diff => +160km pos error, tropo_error => 15m error, iono -2m error
        sv_range[svid] = obs.l1.psr[page] + c * sv_time_diff - tropo_delay
        sv_phase[svid] = -obs.l1.adr[page] + (c * sv_time_diff - tropo_delay) / lambda_l1
    
    # get current state parameters
    rx_ecef_pos = state[:3]
    rx_ecef_vel = state[3:6]
    clock_bias = state[6]
    clock_rate = state[7]
    
    # linearized observation model
    n_svs = len(valid_svids)
    H = zeros((n_svs, 8))
    for i, svid in enumerate(valid_svids):
        r_hat = norm(sv_ecef[svid] - rx_ecef_pos)
        H[i, :3] = (rx_ecef_pos - sv_ecef[svid]) / r_hat
        H[i, 3:] = 0.
        H[i, 6] = 1.  # in meters
        
    # TODO: every time satellite comes into view, need to reset it's P matrix
    
    # calculate Kalman gain
    K = P.dot(H.T).dot(inv(H.dot(P).dot(H.T) + 0.01 * identity(n_svs)))
    # compute innovation
    dz = zeros((n_svs,))
    for i, svid in enumerate(valid_svids):
        # pseudorange
        dz[i] = sv_range[svid] - norm(sv_ecef[svid] - rx_ecef_ref) - clock_bias
        # phase
        #dz[n_svs + i] = sv_phase[svid] - norm(sv_ecef[svid] - rx_ecef_ref) / lambda_l1 - clock_bias / lambda_l1 - integer_ambiguity[i]
    # update state and state covariance
    state = state + K.dot(dz)
    P = (identity(8) - K.dot(H)).dot(P)
    
#     state[3:6] = 0.
    rx_ecef[page, :] = state[:3]
        
print('done')

done


In [32]:
state

array([  1.41027763e+07,  -1.63262664e+07,   3.04624690e+07,
         3.18221421e+03,  -6.71727796e+03,   1.03657222e+04,
         3.36797975e+01,  -1.53469151e-01])

In [33]:
rx_geo = ecef2geo(rx_ecef)
geo_ref = nanmean(bestpos.geo, axis=0)

In [34]:
print(rx_geo[-40:, :])

[[  5.47072228e+01  -4.89888768e+01   3.04709047e+07]
 [  5.47078877e+01  -4.89933594e+01   3.04836022e+07]
 [  5.47085411e+01  -4.89978626e+01   3.04962978e+07]
 [  5.47091829e+01  -4.90023863e+01   3.05089917e+07]
 [  5.47098133e+01  -4.90069307e+01   3.05216836e+07]
 [  5.47104320e+01  -4.90114957e+01   3.05343735e+07]
 [  5.47110392e+01  -4.90160815e+01   3.05470614e+07]
 [  5.47116347e+01  -4.90206879e+01   3.05597472e+07]
 [  5.47122184e+01  -4.90253151e+01   3.05724309e+07]
 [  5.47127905e+01  -4.90299631e+01   3.05851124e+07]
 [  5.47133507e+01  -4.90346320e+01   3.05977918e+07]
 [  5.47138992e+01  -4.90393216e+01   3.06104690e+07]
 [  5.47144358e+01  -4.90440322e+01   3.06231439e+07]
 [  5.47149606e+01  -4.90487638e+01   3.06358164e+07]
 [  5.47154735e+01  -4.90535163e+01   3.06484866e+07]
 [  5.47159744e+01  -4.90582898e+01   3.06611544e+07]
 [  5.47164634e+01  -4.90630843e+01   3.06738197e+07]
 [  5.47169404e+01  -4.90678998e+01   3.06864825e+07]
 [  5.47174052e+01  -4.90727

In [35]:
ecef_diff = norm(rx_ecef - bestpos.ecef, axis=-1)
print(nanmean(ecef_diff))
print(nanmean(rx_ecef, axis=0) - nanmean(bestpos.ecef, axis=0))
print(nanmean(rx_ecef - bestpos.ecef, axis=0))
# print(nanmean(bestpos.ecef, axis=0))
print(geo_ref)

13424233.5169
[  6399133.99942242  -5096324.39107415  10615730.24205882]
[  6399133.99942241  -5096324.39107416  10615730.2420588 ]
[  39.51069808  -84.73228061  293.09594527]


In [ ]:
for page in range(0, SIZE):
    x = Phi * x
    P = Phi * P * Phi.T + Q
    
    # compute H matrix
    
    K = P * H.T * inv(H * P * H.T + R)
    x = x + K * (z - H * x)
    P = (identity(37) - K * H) * P

In [ ]:
    # old LSI estimate loop
    while(norm(dx) > .01 and absolute(db) > .01):
        # compute dp
        x_diff = zeros((len(valid_svids), 3))
        for i, svid in enumerate(valid_svids):
            x_diff[i, :] = sv_ecef[svid] - x0
        x_norm = norm(x_diff, axis=1) # compute norm along rows
        p0 = x_norm + b0
        dp = asarray([sv_range[svid] for svid in valid_svids]) - p0

        # compute geometry matrix
        unit = (x_diff.T / x_norm).T # Nx3 broadcast divide NxNone -> 3xN / Nx1
        g = ones((len(valid_svids), 4))
        g[:, 0:3] = -unit

        # solve for dx and db
        try:
            delta = inv(g.T.dot(g)).dot(g.T).dot(dp)
        except LinAlgError:
            skipped_epochs += 1
            continue
            
        dx = delta[0:3]
        db = delta[3]

        # calculate new x and b
        x0 += dx
        b0 += db

.

.

.

.

.

.

.

In [12]:
# initial state for KF
step = 1.  # step size 1 second (TODO update in loop?)
state = asarray([452703., -4906915., 4036272., 0, 0, 0])  # initial state (position, velocity)
P = 10000 * identity(6)  # state covariance matrix
Phi = identity(6)
Phi[[0, 1, 2], [3, 4, 5]] = step  # transition matrix
q_p = 1.
q_v = 1.
Q = zeros((6, 6))  # process noise matrix (effect of incorrect modeling over time)
Q[0, 0] = Q[1, 1] = Q[2, 2] = q_p * step + q_v * step**3
Q[3, 3] = Q[4, 4] = Q[5, 5] = q_v * step
Q[0, 3] = Q[3, 0] = Q[1, 4] = Q[4, 1] = Q[2, 5] = Q[5, 2] = q_v * step**2 / 2.
# z  # measurement vector
# R  # measurement covariance matrix
# H  # linear relationship of measurement to state
print(state)
print(P)
print(Phi)
print(Q)

[  452703. -4906915.  4036272.        0.        0.        0.]
[[ 10000.      0.      0.      0.      0.      0.]
 [     0.  10000.      0.      0.      0.      0.]
 [     0.      0.  10000.      0.      0.      0.]
 [     0.      0.      0.  10000.      0.      0.]
 [     0.      0.      0.      0.  10000.      0.]
 [     0.      0.      0.      0.      0.  10000.]]
[[ 1.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]
[[ 2.   0.   0.   0.5  0.   0. ]
 [ 0.   2.   0.   0.   0.5  0. ]
 [ 0.   0.   2.   0.   0.   0.5]
 [ 0.5  0.   0.   1.   0.   0. ]
 [ 0.   0.5  0.   0.   1.   0. ]
 [ 0.   0.   0.5  0.   0.   1. ]]


In [20]:
from lightning import Lightning

In [21]:
lgn = Lightning(host='http://192.168.3.137:3000/')

In [22]:
# lgn.create_session('pvt-2')
lgn.use_session(2)

Session number: 2

In [28]:
lgn.plot(data={'latitude': geo_ref[0], 'longitude': geo_ref[1], 
               'api_key': 'AIzaSyDcxotfylh6ylNGW9oj-0sv7y_aUHnY_vU', 'points': rx_geo},
        type='geodetic-scatter-plot')

.

.

.

.