In [20]:
from numpy import pi, zeros, ones, flatnonzero, sin, cos, tan, radians, asarray, sqrt, absolute, column_stack, nan, nanmean
import numpy
npmax = numpy.max
npsum = numpy.sum
from numpy.linalg import norm, inv, LinAlgError

import pytz

from gnss.time import gpstime, utctime
from gnss.parsing import read_novatel_ascii
from gnss.orbits import compute_gps_satellite_position_from_orbital_parameters, compute_gps_orbital_parameters_from_ephemeris
from gnss.coordinates import ecef2geo, ecef2sky, geo2ecef
from gnss.positioning import TroposphereDelayModel, HopfieldModel, SaastomoinenModel, IonosphereDelayModel

In [21]:
# novatel_filepath = './../../data/20131113.gps'   # (phase iono)
# T = 270.65  # K
# P0 = 1028.4  # mbar
# e0 = 709.596 # mbar
# rh = 0.69
# e0 = TroposphereDelayModel.h20_partial_pressure_from_relative_humidity(0.69, 270.65)

# novatel_filepath = './../../data/20131119d.gps'  # 41 deg F, 28 dew point, 1025 hPa barometric pressure  (phase iono)
novatel_filepath = './../../data/20131119a.gps'  # same    (don't use iono on this one)
T = 278    # K
P0 = 1025  # mbar
e0 = 5.19  # mbar
rh = 0.60  # relative humidity
e0 = TroposphereDelayModel.h20_partial_pressure_from_relative_humidity(rh, T)

In [22]:
observations, ephemerides, bestpos = read_novatel_ascii(novatel_filepath)

In [23]:
filedate = utctime(bestpos.time[0])
print(filedate, filedate.astimezone(pytz.timezone('US/Eastern')))

2013-11-19 20:42:23+00:00 2013-11-19 15:42:23-05:00


In [24]:
bestpos.ecef = geo2ecef(bestpos.geo)
rx_geo_ref = bestpos.geo[0, :]
rx_ecef_ref = bestpos.ecef[0, :]
print(rx_geo_ref, rx_ecef_ref)

[  39.51069221  -84.7322822   293.7752    ] [  452407.84641097 -4906865.73686049  4036406.35445183]


    | Hopfield: 16.84m rms | Saastamonien: 12.41m rms  | Old code: 17.92

In [25]:
# tropo_model = HopfieldModel(P0, e0, T, rx_geo_ref[2])
# print(tropo_model.dry_zenith_delay, tropo_model.wet_zenith_delay)
tropo_model = SaastomoinenModel(P0, e0, T, rx_geo_ref[0], rx_geo_ref[2])
print(tropo_model.dry_zenith_delay, tropo_model.wet_zenith_delay)

0.00227831475766 0.0528486997846


In [26]:
c = 299792458.                # Speed of light in vacuum (m/s)
omega_e_dot = 7.2921159e-5    # Earth's andular rotation rate (rad/s)
f_carr_l1 = 1.57542e9         # GPS L1 frequency
f_carr_l2 = 1.22760e9         # GPS L2 frequency
lambda_l1 = c / f_carr_l1
lambda_l2 = c / f_carr_l2

a1 = 2. * f_carr_l2**2 / (f_carr_l1**2 - f_carr_l2**2)  # multipath observation coefficients
a2 = 2. * f_carr_l1**2 / (f_carr_l1**2 - f_carr_l2**2)

cnr_threshold = 30.

In [27]:
SIZE = len(observations[1].time)
print('Total number of observations: {0}'.format(SIZE))

Total number of observations: 3316


In [30]:
# preallocation
sv_ecef = {}
sv_range = {}
rx_ecef = zeros((SIZE, 3))
rx_geo = zeros((SIZE, 3))
dop = zeros((SIZE, 4))

rx_ecef[:] = nan
rx_geo[:] = nan
dop[:] = nan

In [31]:
# %%time
skipped_epochs = 0
rx_clock_bias = 0
for page in range(0, SIZE):
    
    # mask unsuitable svids
    valid_svids = asarray([svid for svid, obs in observations.items() if obs.l1.cnr[page] > cnr_threshold and obs.l1.psr[page] > 0 and obs.l1.psr[page] < 2.6e7])

    # we need at least four valid measurements for positioning
    if len(valid_svids) < 4:
        skipped_epochs += 1
        continue
    
    # clean measurements for each sv
    for svid in valid_svids:
        
        # get relevant observations/ephemerides
        obs = observations[svid]
        eph = ephemerides[svid]
        
        # estimate propagation time
        tau = obs.l1.psr[page] / c
        # estimate transmission time
        sv_time = obs.time[page] - tau - rx_clock_bias  # => + 72m error w/o
        
        # compute satellite position
        u, r, i, Omega, n, E = compute_gps_orbital_parameters_from_ephemeris(eph, sv_time)
        sv_ecef[svid] = compute_gps_satellite_position_from_orbital_parameters(u, r, i, Omega)

        # compute satellite clock drift error and relativistic corrections
        sv_time_correction_epoch = eph.zweek * 604800 + eph.t_oc
        elapsed_time = sv_time - sv_time_correction_epoch

        sv_time_diff = eph.a0 + eph.a1 * elapsed_time + eph.a2 * elapsed_time**2 \
                        - 4.442807633e-10 * eph.e * sqrt(eph.a) * sin(E)

        # compute satellite sky coordinates to get obliquity
        sv_sky = ecef2sky(rx_ecef_ref, sv_ecef[svid])
        el = radians(sv_sky[1])
        
        # correct ECEF for Earth rotation
        theta = omega_e_dot * tau
        rot_omega_e = asarray([[cos(theta), sin(theta), 0],
                               [-sin(theta), cos(theta), 0],
                               [0, 0, 1]])
        sv_ecef[svid] = rot_omega_e.dot(sv_ecef[svid].T).T  # <-- 300m satellite pos error w/o => +20m rx pos error

        # compute partially cleaned carrier phase measurements (for iono error--better than psr, clock stuff doesn't matter)
        adr_l1_c = obs.l1.adr[page] + c * sv_time_diff / lambda_l1
        adr_l2_c = obs.l2.adr[page] + c * sv_time_diff / lambda_l2
        
        # compute tec and ionospheric/tropospheric delays
        tropo_delay = tropo_model.delay(el)
#         iono_delay = IonosphereDelayModel.compute_delay(f_carr_l1, f_carr_l2, obs.l1.psr[page], obs.l2.psr[page])  # prefers adding delay
        iono_delay = IonosphereDelayModel.compute_delay_from_phase(f_carr_l1, f_carr_l2, adr_l1_c, adr_l2_c)

        # mask erroneous error calculations
        if(absolute(tropo_delay) > 30):
            tropo_delay = 0
        if(absolute(iono_delay) > 30):
            iono_delay = 0
            
        # compute cleaned pseudorange; sv_time_diff => +160km pos error, tropo_error => 15m error, iono -2m error
        sv_range[svid] = obs.l1.psr[page] + c * sv_time_diff - tropo_delay# - iono_delay

    # initial estimates for receiver state
    x0 = zeros((1, 3)) # position estimate
    b0 = 0.0                  # clock bias estimate
    dx = 1.0e6 * ones((1,3))  # position error
    db = 1.0e6                # receiver clock bias error
    
    while(norm(dx) > .01 and absolute(db) > .01):
        # compute dp
        x_diff = zeros((len(valid_svids), 3))
        for i, svid in enumerate(valid_svids):
            x_diff[i, :] = sv_ecef[svid] - x0
        x_norm = norm(x_diff, axis=1) # compute norm along rows
        p0 = x_norm + b0
        dp = asarray([sv_range[svid] for svid in valid_svids]) - p0

        # compute geometry matrix
        unit = (x_diff.T / x_norm).T # Nx3 broadcast divide NxNone -> 3xN / Nx1
        g = ones((len(valid_svids), 4))
        g[:, 0:3] = -unit

        # solve for dx and db
        try:
            delta = inv(g.T.dot(g)).dot(g.T).dot(dp)
        except LinAlgError:
            skipped_epochs += 1
            continue
            
        dx = delta[0:3]
        db = delta[3]

        # calculate new x and b
        x0 += dx
        b0 += db

    rx_ecef[page, :] = x0
    rx_geo[page, :] = ecef2geo(x0)
    rx_clock_bias = b0 / c

    # compute dop
    lat = radians(rx_geo[page, 0])
    lon = radians(rx_geo[page, 1])
    rx_rot = asarray([[-sin(lon),            cos(lon),             0,        0],
                      [-sin(lat) * cos(lon), -sin(lat) * sin(lon), cos(lat), 0],
                      [cos(lat) * cos(lon),  cos(lat) * sin(lon),  sin(lat), 0],
                      [0,                    0,                    0,        1]]);
    g_rot = g.dot(rx_rot)
    try:
        h_rot = inv(g_rot.dot(g_rot.T))
        dop[page, :] = asarray([h_rot[0,0], h_rot[1,1], h_rot[2,2], h_rot[3,3]])
    except LinAlgError:
        continue

    # compute multipath observable
#     o1[valid_prns, page] = obs.l1.psr[valid_svids, page] - obs.l1.adr[valid_svids, page] \
#                         - a1 * (obs.l1.adr[valid_svids, page] - obs.l2.adr[valid_svids, page])
#     o2[valid_prns, page] = obs.l2.psr[valid_svids, page] - obs.l2.adr[valid_svids, page] \
#                         - a2 * (obs.l1.adr[valid_svids, page] - obs.l2.adr[valid_svids, page])

print('done')

done


In [32]:
b0

34.030738782959432

In [24]:
rx_geo = ecef2geo(rx_ecef)

In [25]:
nanmean(ecef2geo(bestpos.ecef), axis=0)

array([  39.51069808,  -84.73228061,  293.09629123])

In [26]:
geo_ref = nanmean(bestpos.geo, axis=0)

In [27]:
ecef_diff = rx_ecef - bestpos.ecef[:SIZE, :]
print(norm(nanmean(ecef_diff, axis=0)))
print(nanmean(rx_ecef, axis=0) - nanmean(bestpos.ecef, axis=0))
print(nanmean(ecef_diff, axis=0))
print(nanmean(bestpos.ecef, axis=0))
print(geo_ref)

9.25370500423
[ 2.32590552 -6.0447522   6.60925041]
[ 2.32590552 -6.04475218  6.6092504 ]
[  452407.89597717 -4906864.78969364  4036406.42501342]
[  39.51069808  -84.73228061  293.09594527]


In [29]:
rx_clock_bias * c

34.030738782959432

.

.

.

.

.

.

.

In [94]:
from lightning import Lightning

In [17]:
lgn = Lightning(host='http://192.168.3.137:3000/')

In [75]:
# lgn.create_session('pvt-2')
lgn.use_session(2)

Session number: 2

In [95]:
lgn.plot(data={'latitude': geo_ref[0], 'longitude': geo_ref[1], 
               'api_key': 'AIzaSyDcxotfylh6ylNGW9oj-0sv7y_aUHnY_vU', 'points': rx_geo},
        type='geodetic-scatter-plot')

.

.

.

.

In [314]:
nanmean(bestpos.ecef, axis=0)

array([  452406.63901629, -4906863.97955478,  4036405.05290695])

In [ ]:
static: 452404.475, -4906838.703,  4036384.991

old: 452407.89597717, -4906864.78969364,  4036406.42501342
    
new: 452406.63901629, -4906863.97955478,  4036405.05290695